### ISSUE TITLE
Online version no longer available

### ISSUE THREAD

**Issue by meichthys** [tuomas2/sword_studybibles#10]
The readme points to an online version of this script, but the link is either broken, or the service is no longer available.

**Comment by tuomas2** [comment]
Yes, should update README. It is no longer available, there were not many users and it was a security risk for my server because I did not maintain it. But you can download the tool and run it locally.

**Comment by meichthys** [comment]
I was able to run it locally, but it was not successful, perhaps because the rpib format was not comparable.

I was attempting to convert the nkjv epub files on archive.org (https://archive.org/download/nkjvstudybible).

**Comment by tuomas2** [comment]
Tool is not generic by any means but specifically for epub files published by crossway. (not sure if other modules that use same toolchain that crossway uses could work). 

You can use epub directly with AndBible via it's epub support.

**Comment by meichthys** [comment]
OK thanks. I was able to import the epub fine, but navigating is difficult since book, chapter, verse selection isn't possible, only a very long table of contents. Is it possible to modify the epub file in such a way that chapters and verses are recognized and navigable in Andbible like normal bible modules?

**Comment by tuomas2** [comment]
No, support is made as a generic book.
