### ISSUE TITLE
EPUB to Sword conversion fails

### ISSUE THREAD

**Issue by FutureLinkOpenSource** [tuomas2/sword_studybibles#4]
We're testing the conversion of the MacArthur Study Bible to Sword, which is supposed to work based on the documentation. However, upon running the command to convert it, we get:

> ~/.local/lib/python3.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
> 
> The code that caused this warning is on line 13 of the file studybible_to_osis.py. To get rid of this warning, change code that looks like this:
> 
>  BeautifulSoup(YOUR_MARKUP})
> 
> to this:
> 
>  BeautifulSoup(YOUR_MARKUP, "lxml")
> 
>   markup_type=markup_type))
> Exception('No studynotes in zip file')
> > ~/.local/lib/python3.7/site-packages/study2osis-0.0.5-py3.7.egg/study2osis/main.py(167)read_studynotes()
>     166         if not studynote_files:
> --> 167             raise Exception('No studynotes in zip file')
>     168 
> 
> ipdb> 

If you need any other information, like package versions used, let us know.

**Comment by tuomas2** [comment]
It looks like the epub file is not what the script expects it to be. Where did you obtain epub file? 
It should be epub purchased from crosswire (esv.org).

**Comment by FutureLinkOpenSource** [comment]
Thanks for your prompt response. This EPUB (and the modified one we're testing) is NKJV (not ESV) and from the publisher Thomas Nelson (not Crossway). Do you have any feature planned to make this package work with that bible?

**Comment by tuomas2** [comment]
EPUB is pretty general format. This software works (or could be adapted to work) with EPUB files generated by the software Crossway has been using to make epub-versions of their bibles. I have no plans to work on this or other related conversion projects.

**Comment by FutureLinkOpenSource** [comment]
-
